CREATE INDEX "RALUCA"."ID_USER_ANNOUNCEMENTS" ON "RALUCA"."PF_ANNOUNCEMENTS" ("ID_USER") ;
/
CREATE INDEX "CITY_ANNOUNCEMENTS" ON "RALUCA"."PF_ANNOUNCEMENTS" ("CITY") ;
/
CREATE INDEX "RALUCA"."EMAIL_PASSWORD_INDEX_01" ON "RALUCA"."PF_USERS" ("EMAIL", "PASSWORD") ;
/
CREATE INDEX "ID_USER_FAV_ANNOUNCEMENTS" ON "RALUCA"."PF_FAV_ANNOUNCEMENTS" ("ID_USER") ;
/
CREATE INDEX "CREATION_DATE_PF_ANNOUNCEMENTS" ON "RALUCA"."PF_ANNOUNCEMENTS" ("CREATION_DATE");
/

CREATE BITMAP INDEX PF_MESSAGES_ANNOUNCEMENT
ON    PF_ANNOUNCEMENTS(ID)
FROM  PF_ANNOUNCEMENTS, PF_MESSAGES
WHERE PF_ANNOUNCEMENTS.ID = PF_MESSAGES.ID_ANNOUNCEMENT;
/

CREATE BITMAP INDEX PF_ATTACHEMENTS_ANNOUNCEMENT
ON    PF_ANNOUNCEMENTS(ID)
FROM  PF_ANNOUNCEMENTS, PF_ATTACHEMENTS
WHERE PF_ANNOUNCEMENTS.ID = PF_ATTACHEMENTS.ID_ANNOUNCEMENT;
/

